
[project]
name = "arkadiko"

[contracts.arkadiko-dao-token-trait]
depends_on = []
path = "contracts/arkadiko-dao-token-trait.clar"

[contracts.arkadiko-token]
depends_on = ["arkadiko-mock-ft-trait", "arkadiko-dao-token-trait"]
path = "contracts/arkadiko-token.clar"

[contracts.arkadiko-auction-engine]
depends_on = ["arkadiko-oracle", "xusd-token", "arkadiko-freddie", "arkadiko-mock-ft-trait", "arkadiko-vault-trait", "arkadiko-auction-engine-trait"]
path = "contracts/arkadiko-auction-engine.clar"

[contracts.arkadiko-auction-engine-trait]
depends_on = []
path = "contracts/arkadiko-auction-engine-trait.clar"

[contracts.arkadiko-collateral-types-trait]
depends_on = []
path = "contracts/arkadiko-collateral-types-trait.clar"

[contracts.arkadiko-collateral-types]
depends_on = ["arkadiko-collateral-types-trait"]
path = "contracts/arkadiko-collateral-types.clar"

[contracts.arkadiko-vault-data]
depends_on = ["arkadiko-diko-guardian"]
path = "contracts/arkadiko-vault-data.clar"

[contracts.dao]
depends_on = ["arkadiko-token", "arkadiko-collateral-types", "arkadiko-vault-trait"]
path = "contracts/arkadiko-dao.clar"

[contracts.governance]
depends_on = ["arkadiko-token", "arkadiko-mock-ft-trait"]
path = "contracts/arkadiko-governance.clar"

[contracts.freddie]
depends_on = [
  "arkadiko-collateral-types",
  "arkadiko-stx-reserve",
  "arkadiko-vault-trait",
  "arkadiko-mock-ft-trait",
  "arkadiko-vault-manager-trait",
  "arkadiko-sip10-reserve",
  "arkadiko-stacker",
  "arkadiko-vault-data",
  "arkadiko-vault-rewards"
]
path = "contracts/arkadiko-freddie.clar"

[contracts.arkadiko-liquidator]
depends_on = ["arkadiko-collateral-types", "arkadiko-dao", "arkadiko-vault-manager-trait", "arkadiko-auction-engine-trait"]
path = "contracts/arkadiko-liquidator.clar"

[contracts.arkadiko-mock-ft-trait]
depends_on = []
path = "contracts/arkadiko-mock-ft-trait.clar"

[contracts.arkadiko-oracle]
depends_on = ["arkadiko-oracle-trait"]
path = "contracts/arkadiko-oracle.clar"

[contracts.arkadiko-oracle-trait]
depends_on = []
path = "contracts/arkadiko-oracle-trait.clar"

[contracts.arkadiko-stacker]
depends_on = ["arkadiko-stacker-trait", "arkadiko-vault-data"]
path = "contracts/arkadiko-stacker.clar"

[contracts.arkadiko-stacker-trait]
depends_on = []
path = "contracts/arkadiko-stacker-trait.clar"

[contracts.arkadiko-stx-reserve]
depends_on = ["arkadiko-collateral-types", "arkadiko-oracle", "arkadiko-dao", "xusd-token", "arkadiko-mock-ft-trait", "arkadiko-vault-trait"]
path = "contracts/arkadiko-stx-reserve.clar"

[contracts.arkadiko-vault-trait]
depends_on = ["arkadiko-mock-ft-trait"]
path = "contracts/arkadiko-vault-trait.clar"

[contracts.arkadiko-vault-manager-trait]
depends_on = []
path = "contracts/arkadiko-vault-manager-trait.clar"

[contracts.xusd-token]
depends_on = ["arkadiko-mock-ft-trait", "arkadiko-dao"]
path = "contracts/xusd-token.clar"

[contracts.xstx-token]
depends_on = ["arkadiko-mock-ft-trait"]
path = "contracts/xstx-token.clar"

[contracts.arkadiko-sip10-reserve]
depends_on = ["arkadiko-collateral-types", "arkadiko-mock-ft-trait", "arkadiko-vault-trait", "arkadiko-oracle", "arkadiko-dao", "xusd-token", "xstx-token"]
path = "contracts/arkadiko-sip10-reserve.clar"

[contracts.stake-registry]
depends_on = ["arkadiko-token", "arkadiko-stake-pool-trait", "arkadiko-mock-ft-trait"]
path = "contracts/arkadiko-stake-registry.clar"

[contracts.arkadiko-stake-pool-trait]
depends_on = ["arkadiko-mock-ft-trait"]
path = "contracts/arkadiko-stake-pool-trait.clar"

[contracts.arkadiko-stake-pool-diko]
depends_on = ["arkadiko-stake-pool-trait", "arkadiko-token", "arkadiko-mock-ft-trait", "arkadiko-stake-registry"]
path = "contracts/arkadiko-stake-pool-diko.clar"

[contracts.arkadiko-diko-guardian]
depends_on = ["arkadiko-token"]
path = "contracts/arkadiko-diko-guardian.clar"

[contracts.arkadiko-vault-rewards]
depends_on = ["arkadiko-token"]
path = "contracts/arkadiko-vault-rewards.clar"
