
[project]
name = "arkadiko"

[contracts.arkadiko-token]
depends_on = ["mock-ft-trait"]
path = "contracts/arkadiko-token.clar"

[contracts.auction-engine]
depends_on = ["oracle", "xusd-token", "freddie", "mock-ft-trait", "vault-trait", "auction-engine-trait"]
path = "contracts/auction-engine.clar"

[contracts.auction-engine-trait]
depends_on = []
path = "contracts/auction-engine-trait.clar"

[contracts.collateral-types-trait]
depends_on = []
path = "contracts/collateral-types-trait.clar"

[contracts.collateral-types]
depends_on = ["collateral-types-trait"]
path = "contracts/collateral-types.clar"

[contracts.dao]
depends_on = ["arkadiko-token", "collateral-types", "vault-trait", "mock-pox"]
path = "contracts/dao.clar"

[contracts.freddie]
depends_on = ["collateral-types", "stx-reserve", "vault-trait", "mock-ft-trait", "vault-manager-trait", "sip10-reserve"]
path = "contracts/freddie.clar"

[contracts.liquidator]
depends_on = ["collateral-types", "dao", "vault-manager-trait", "auction-engine-trait"]
path = "contracts/liquidator.clar"

[contracts.mock-ft-trait]
depends_on = []
path = "contracts/mock-ft-trait.clar"

[contracts.mock-pox]
depends_on = []
path = "contracts/mock-pox.clar"

[contracts.oracle]
depends_on = ["oracle-trait"]
path = "contracts/oracle.clar"

[contracts.oracle-trait]
depends_on = []
path = "contracts/oracle-trait.clar"

[contracts.stacker-registry]
depends_on = []
path = "contracts/stacker-registry.clar"

[contracts.stacker]
depends_on = []
path = "contracts/stacker.clar"

[contracts.stx-reserve]
depends_on = ["collateral-types", "oracle", "dao", "xusd-token", "mock-ft-trait", "vault-trait"]
path = "contracts/stx-reserve.clar"

[contracts.vault-trait]
depends_on = ["mock-ft-trait"]
path = "contracts/vault-trait.clar"

[contracts.vault-manager-trait]
depends_on = []
path = "contracts/vault-manager-trait.clar"

[contracts.xusd-token]
depends_on = ["mock-ft-trait", "dao"]
path = "contracts/xusd-token.clar"

[contracts.xstx-token]
depends_on = ["mock-ft-trait"]
path = "contracts/xstx-token.clar"

[contracts.sip10-reserve]
depends_on = ["collateral-types", "mock-ft-trait", "vault-trait", "oracle", "dao", "xusd-token", "xstx-token"]
path = "contracts/sip10-reserve.clar"
