
[project]
name = "arkadiko"

[contracts.arkadiko-dao-token-trait-v1]
depends_on = []
path = "contracts/arkadiko-dao-token-trait-v1.clar"

[contracts.arkadiko-mock-ft-trait-v1]
depends_on = []
path = "contracts/arkadiko-mock-ft-trait-v1.clar"

[contracts.arkadiko-collateral-types-v1-1]
depends_on = ["arkadiko-collateral-types-trait-v1"]
path = "contracts/arkadiko-collateral-types-v1-1.clar"

[contracts.arkadiko-dao]
depends_on = ["arkadiko-token", "arkadiko-collateral-types-v1-1", "arkadiko-vault-trait-v1"]
path = "contracts/arkadiko-dao.clar"

[contracts.arkadiko-token]
depends_on = ["arkadiko-mock-ft-trait-v1", "arkadiko-dao-token-trait-v1"]
path = "contracts/arkadiko-token.clar"

[contracts.arkadiko-oracle-trait-v1]
depends_on = []
path = "contracts/arkadiko-oracle-trait-v1.clar"

[contracts.arkadiko-oracle-v1-1]
depends_on = ["arkadiko-oracle-trait-v1"]
path = "contracts/arkadiko-oracle-v1-1.clar"

[contracts.arkadiko-vault-data-v1-1]
depends_on = ["arkadiko-diko-guardian-v1-1"]
path = "contracts/arkadiko-vault-data-v1-1.clar"

[contracts.arkadiko-diko-guardian-v1-1]
depends_on = ["arkadiko-token"]
path = "contracts/arkadiko-diko-guardian-v1-1.clar"

[contracts.arkadiko-vault-trait-v1]
depends_on = ["arkadiko-mock-ft-trait-v1"]
path = "contracts/arkadiko-vault-trait-v1.clar"

[contracts.arkadiko-vault-manager-trait-v1]
depends_on = ["arkadiko-vault-trait-v1"]
path = "contracts/arkadiko-vault-manager-trait-v1.clar"

[contracts.arkadiko-auction-engine-trait-v1]
depends_on = ["arkadiko-oracle-trait-v1", "arkadiko-vault-manager-trait-v1"]
path = "contracts/arkadiko-auction-engine-trait-v1.clar"

[contracts.arkadiko-collateral-types-trait-v1]
depends_on = []
path = "contracts/arkadiko-collateral-types-trait-v1.clar"
